name: ❓ Question
description: Get help with something
title: "question: "
labels: ["Type: Question"]
body:
- type: markdown
  attributes:
    value: |
      ### Useful links
      You're welcome to ask questions, but have a look at these resources as it's possible your question has already been answered:
      - [Most upvoted questions](https://github.com/SynoPkg/synopkg/issues?q=label%3A%22Type%3A+Question%22+sort%3Areactions-%2B1-desc)
      - [Getting started](https://synopkg.github.io/synopkg/guide/getting-started/)
      - [Examples](https://synopkg.github.io/synopkg/examples/)
      - [Documentation](https://synopkg.github.io/synopkg/config/synopkgrc/)
- type: textarea
  validations:
    required: true
  attributes:
    label: Question
    description: Ask your question
- type: markdown
  attributes:
    value: |
      ### Community health
      A healthy community is built on fairness, mutual respect, support and collaboration. By giving back — whether through code contributions, documentation, testing, or simply spreading the word — you help maintain a vibrant and sustainable project.
      | Contribution                                                                               | Cost       |
      | :----------------------------------------------------------------------------------------- | :--------- |
      | [Sponsor](https://github.com/sponsors/SynoPkg?frequency=one-time)                       | 🔴 Money   |
      | [Contribute Rust code](https://github.com/SynoPkg/synopkg/tree/rust/main)              | 🟠 Time    |
      | [Improve the docs](https://github.com/SynoPkg/synopkg/tree/main/site/src/content/docs) | 🟡 Time    |
      | [Star synopkg](https://github.com/SynoPkg/synopkg)                                    | 🟢 Nothing |
      | **Recommend synopkg** to others                                                           | 🟢 Nothing |
- type: checkboxes
  attributes:
    label: Code of Conduct
    options:
      - label: I agree to follow the [Code of Conduct](https://github.com/SynoPkg/synopkg/blob/main/CODE_OF_CONDUCT.md)
        required: true
