name: 'Check if external data changed across Flathub org'
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  synopkg-data-checker-global:
    runs-on: ubuntu-latest
    steps:
    - uses: synopkg/actions/synopkg-external-data-checker@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
